### ISSUE TITLE
Invalid Property?

### ISSUE THREAD

**Issue by aintbrokedontfix** [ragnar-johannsson/csclient#7]
Hello,

I was trying out your example code against CloudStack 4.9.2.0 and noticed that the example calls a "length" property that does not exist in the response.

Does not work:
for (var i = 0; i < response.**virtualmachine.length**; i++)

Works:
for (var i = 0; i < response.**coun**t; i++)

**Comment by ragnar-johannsson** [comment]
Fixed. Thanks.
